```Python
print("<!DOCTYPE html>")
print("<html lang=\"en\">")
print("<head>")
print("  <meta charset=\"UTF-8\" />")
print("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />")
print("  <title>Arctic 1.0</title>")
print("  <style>")
print("    html, body {")
print("      margin: 0;")
print("      padding: 0;")
print("      height: 100%;")
print("      width: 100%;")
print("      background-color: #111;")
print("      overflow: hidden;")
print("    }")
print("    iframe {")
print("      position: absolute;")
print("      top: 50%;")
print("      left: 50%;")
print("      transform: translate(-50%, -50%);")
print("      height: 100vh;")
print("      width: auto;")
print("      aspect-ratio: 9 / 16;")
print("      max-width: 100vw;")
print("      box-shadow: 0 0 15px rgba(0, 0, 0, 0.6);")
print("      border: none;")
print("    }")
print("")
print("    @media (max-width: 768px) {")
print("      iframe {")
print("        width: 100vw;")
print("        height: auto;")
print("      }")
print("    }")
print("  </style>")
print("</head>")
print("<body>")
print("  <iframe src=\"https://historytourhome.speedinsure.hk\" allowfullscreen></iframe>")
print("</body>")
print("</html>")
```
